### ISSUE TITLE
ERROR: failed to solve: failed to read dockerfile

### ISSUE THREAD

**Issue by SharbelOkzan** [jddeep/Flutter-Runner#3]
Hello, I'm new to Github actions, so probably the issue is in my workflow not your setup, anyway I'd appreciate if you can help, this is my workflow content:

[.github/workflows/build.yml](https://github.com/SharbelOkzan/Easy-Poker/blob/b6fd5b7af77083b571bbd083b740e42e96ce21f2/.github/workflows/build.yml) :

 ```
name: flutter_build

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: depend on flutter 
      uses: jddeep/Flutter-Runner@56254d611d8b799e297ab6f81ab4ec5dd0d128a2
    - name: test
      run: echo "test"
```
I'm getting this error:
```
ERROR: failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount3951485638/Dockerfile: no such file or directory
```

logs:
[0_build.txt](https://github.com/jddeep/Flutter-Runner/files/13370582/0_build.txt)

If you see what am I doing wrong, please let me know. Thanks!
